### ISSUE TITLE
Ошибка при запросе списка товаров

### ISSUE THREAD

**Issue by ownikss** [IvanAKuzhelev/mongo-warehouse#2]
На скрине ниже в `Promise.all` передается два элемента - результат выполнения функции `countDocuments` и результат выполнения `limit`. Обе эти функции возвращают не возвращают Promise, поэтому `Promise.all` отрабатывает "мгновенно". Иногда колбеки в этих функциях успевают отработать из-за асинхронности. При этом колбек никаким образом не блокирует выполнение Promise.all

<img width="751" alt="Screenshot 2021-06-21 at 13 52 49" src="https://user-images.githubusercontent.com/17406989/122751076-f8bd9200-d297-11eb-927c-46fc6ee75103.png">

Для того чтобы отрабатывало корректно нужно использовать именно Promise, а не колбеки - использовать exec (https://mongoosejs.com/docs/api.html#model_Model.find)

**Comment by capybarish-dev** [comment]
Понятно, спасибо большое, учту и переработаю
